dispatcher:
  name: "default"
  concurrency_num: 2
datasets:
  - name: "cpo_data"
    data: "demo/data.json"
    prompt: "demo/preference_prompt.yaml"
    prompt_type: "preference"
    preprocess: "default"
adapters:
  - name: "lora_cpo"
    type: "lora"
    path: "adapters/lora_cpo"
    optimizer: "adamw"
    lr: 3e-4
    r: 32
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: false
      down_proj: false
      up_proj: false
  - name: "loraplus_cpo"
    type: "loraplus"
    path: "adapters/loraplus_cpo"
    optimizer: "adamw"
    lr_ratio: 8
    lr: 3e-4
    r: 32
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: false
      down_proj: false
      up_proj: false
tasks:
  - type: "cpo"
    name: "task_0"
    adapter: "lora_cpo"
    dataset: "cpo_data"
    batch_size: 16
    mini_batch_size: 16
    num_epochs: 10
    cutoff_len: 256
    save_step: 2000
    loss_type: "sigmoid"
    beta: 0.1
    label_smoothing: 0.0
  - type: "cpo"
    name: "task_1"
    adapter: "loraplus_cpo"
    dataset: "cpo_data"
    batch_size: 16
    mini_batch_size: 16
    num_epochs: 10
    cutoff_len: 256
    save_step: 2000
    loss_type: "hinge"
    beta: 0.1
    label_smoothing: 0.0
