dispatcher:
  name: "default"
  concurrency_num: 2
datasets:
  - name: "dpo_data"
    data: "demo/data.json"
    prompt: "demo/preference_template.json"
    preprocess: "default"
adapters:
  - name: "lora_dpo"
    type: "loraplus"
    path: "adapters/loraplus_sft_dpo"
    optimizer: "adamw"
    lr_ratio: 8
    lr: 3e-4
    r: 32
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: false
      down_proj: false
      up_proj: false
  - name: "lora_0"
    type: "lora"
    path: "adapters/loraplus_sft_0"
    r: 32
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: false
      down_proj: false
      up_proj: false
tasks:
  - type: "dpo"
    name: "task_0"
    adapter: "lora_dpo"
    reference: "lora_0"
    dataset: "dpo_data"
    batch_size: 16
    mini_batch_size: 16
    num_epochs: 10
    cutoff_len: 256
    save_step: 2000
    loss_type: "sigmoid"
    beta: 0.1
    label_smoothing: 0.0
