FROM yezhengmaolove/mlora:latest

MAINTAINER YeZhengMao <yezhengmaolove@gmail.com>

WORKDIR /mLoRA

RUN git pull \
    && /usr/bin/echo -e '#!/bin/bash\neval "$(pyenv init -)"\neval "$(pyenv virtualenv-init -)"\npython mlora_server.py --base_model $BASE_MODEL --root $STORAGE_DIR' | tee /opt/deploy.sh

ENV PYENV_ROOT=/root/.pyenv
ENV PATH "$PYENV_ROOT/bin/:$PATH"

CMD /bin/bash /opt/deploy.sh