dispatcher:
  name: "default"
  concurrency_num: 2
datasets:
  - name: "dummy_data"
    data: "demo/dummy_data.json"
    prompt: "demo/dummy_template.json"
    preprocess: "default"
adapters:
  - type: "lora"
    name: "lora_0"
    path: "adapters/lora_sft_0"
    optimizer: "adamw"
    lr: 3e-4
    r: 32
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: false
      down_proj: false
      up_proj: false
  - type: "lora"
    name: "lora_1"
    path: "adapters/lora_sft_1"
    optimizer: "adamw"
    lr: 3e-4
    lrscheduler: "cosine"
    t_max: 10000
    eta_min: 0
    r: 8
    alpha: 16
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: true
      down_proj: true
      up_proj: true
tasks:
  - type: "train"
    adapter: "lora_0"
    dataset: "dummy_data"
    batch_size: 64
    mini_batch_size: 64
    num_epochs: 10
    cutoff_len: 256
    save_step: 2000
  - type: "train"
    adapter: "lora_1"
    dataset: "dummy_data"
    batch_size: 64
    mini_batch_size: 64
    num_epochs: 10
    cutoff_len: 256
    save_step: 2000
