name: Test LLM Models

on: [push, pull_request]

jobs:
  test-lora:
    runs-on: self-hosted
    container:
      image: mikecovlee/mlora:0.2.1.dev1
      volumes:
        - /home/lab/models:/host_models/
      options: --gpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          bash install_linux.sh
      - name: The unit test of generate.py
        run: |
          python test_generate.py
      - name: The unit test of prompter
        run: |
          python test_prompter.py
      - name: The unit test of tokenizer.py
        run: |
          python test_tokenizer.py
      - name: The unit test of checkpoint.py
        run: |
          python test_checkpoint.py
