name: Clean code test

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - "main"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[ci_test]
      - name: CCN with Lizard
        run: |
          lizard -l python ./mlora -C 12
      - name: Lint with flake8
        run: |
          flake8 ./mlora --count --show-source --statistics --max-line-length=88 --max-complexity 15 --ignore=E203,W503,E704
      - name: Lint with black
        run: |
          black --check ./mlora
      - name: Lint with isort
        run: |
          isort ./mlora --check --profile black
      - name: Static code check with mypy
        run: |
          mypy ./mlora --ignore-missing-imports --non-interactive --install-types --check-untyped-defs
      - name: Test with pytest
        run: |
          pytest
